[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
smart = "BLYzT5n6WtwteMkNUQEtcRKyCVQys8Y3wbG1BESQannT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./devnet.json"
#wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
